### ISSUE TITLE
Baseline calculation fails due to null date 

### ISSUE THREAD

**Issue by Elchi3** [ddbeck/strict-browser-compat-data#2]
@ddbeck Looks like you switched to Temporal. I updated to latest main and installed dependencies but yet I got an error when trying to calculate baseline...

```
npx tsx ./scripts/baseline/ javascript.builtins.Map.@@species

/Users/florianscholz/dev/strict-browser-compat-data/node_modules/@js-temporal/polyfill/lib/ecmascript.ts:488
  if (!match) throw new RangeError(`invalid ISO 8601 string: ${isoString}`);
                    ^
RangeError: invalid ISO 8601 string: null
    at ParseISODateTime (/Users/florianscholz/dev/strict-browser-compat-data/node_modules/@js-temporal/polyfill/lib/ecmascript.ts:488:21)
    at ParseTemporalDateString (/Users/florianscholz/dev/strict-browser-compat-data/node_modules/@js-temporal/polyfill/lib/ecmascript.ts:574:10)
    at ES.ToTemporalDate (/Users/florianscholz/dev/strict-browser-compat-data/node_modules/@js-temporal/polyfill/lib/ecmascript.ts:1464:43)
    at static (/Users/florianscholz/dev/strict-browser-compat-data/node_modules/@js-temporal/polyfill/lib/plaindate.ts:319:17)
    at isBaselineHighRelease (/Users/florianscholz/dev/strict-browser-compat-data/scripts/baseline/calculate-status.ts:166:29)
    at <anonymous> (/Users/florianscholz/dev/strict-browser-compat-data/scripts/baseline/calculate-status.ts:170:42)
    at Array.filter (<anonymous>)
    at <anonymous> (/Users/florianscholz/dev/strict-browser-compat-data/scripts/baseline/calculate-status.ts:170:28)
    at Array.map (<anonymous>)
    at <anonymous> (/Users/florianscholz/dev/strict-browser-compat-data/scripts/baseline/calculate-status.ts:170:4)

Node.js v20.9.0
```

**Comment by ddbeck** [comment]
I'm getting ready to archive this repo, so I'm going to close this. I'm pretty sure we dealt with this or did so in web-features, where all this stuff has moved anyway. Thanks!
